name: MakeCode Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build
        run: npx makecode build -j

      - name: Prepare for Deployment
        run: |
          mkdir deploy
          cp -r web/* deploy/
          mkdir -p deploy/built
          if [ -f built/binary.js ]; then
            cp built/binary.js deploy/built/
          elif [ -f built/common-js/binary.js ]; then
            cp built/common-js/binary.js deploy/built/
          else
            echo "Error: built/binary.js not found"
            ls -R built
            exit 1
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy

      - name: Deploy to Itch.io
        run: docker run --rm -v ${{ github.workspace }}/deploy:/deploy -e BUTLER_API_KEY=${{ secrets.BUTLER_API_KEY }} itchio/butler push /deploy fdreger/tom-rider:web
