name: MakeCode Build
on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build
        run: npx makecode

      - name: Prepare for Deployment
        run: |
          mkdir deploy
          cp -r web/* deploy/
          mkdir -p deploy/built
          cp built/binary.js deploy/built/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./deploy

      - name: Deploy to Itch.io
        uses: Ayush-Bharadwaj/butler-publish-action@v1.0.3
        with:
          butler_key: ${{ secrets.BUTLER_API_KEY }}
          itch_user: fdreger
          itch_game: tom-rider
          package: ./deploy
          channel: web
